
const data={
 cities:[
  ["osaka","🐙","Osaka","Oct 7–10","Sotetsu Grand Fresa Osaka Namba","3 nights"],
  ["kyoto","⛩","Kyoto","Oct 10–12","Hotel Resol Kyoto Kawaramachi Sanjo","2 nights"],
  ["fuji","🗻","Fuji","Oct 12–14","Fujisan Onsen Hotel Kaneyamaen","2 nights"],
  ["tokyo","🗼","Tokyo","Oct 14–21","Daiwa Roynet Hotel Ginza PREMIER","7 nights"],
  ["seoul","🏙","Seoul","Oct 21–25","LOTTE CITY HOTEL MYEONGDONG","4 nights"]
 ],
 stays:{
  osaka:["Sotetsu Grand Fresa Osaka Namba","1-1-13, Nippombashi, Chuo-ku, Osaka, Japan, 542-0073","中央区日本橋1-1-13, 大阪, 日本, 542-0073","Oct 7 after 3:00 PM","Oct 10 before 11:00 AM","Riya Bhangale","Economy Double Room · Non-Smoking","Free cancellation before Oct 6","https://www.google.com/maps/search/?api=1&query=Sotetsu+Grand+Fresa+Osaka+Namba"],
  kyoto:["Hotel Resol Kyoto Kawaramachi Sanjo","59-1 Daikokucho, Nakagyo, Kyoto, Japan, 604-8031","中京区河原町通三条下る大黒町59-1, 京都, 日本","Oct 10 after 3:00 PM","Oct 12 before 11:00 AM","Riya Bhangale","Double Room · Non Pet Friendly","Free cancellation until Oct 6 11:59 PM","https://www.google.com/maps/search/?api=1&query=Hotel+Resol+Kyoto+Kawaramachi+Sanjo"],
  fuji:["Fujisan Onsen Hotel Kaneyamaen","9-1-18 Kamiyoshida Higashi, Fujiyoshida, Yamanashi","9-1-18 Kamiyoshida Higashi","Oct 12 after 3:00 PM","Oct 14 before 10:00 AM","AAKASH IYER","Japanese Style Room with Open-Air Bath Mount Fuji View","Free cancellation until Oct 1","https://maps.google.com/?q=Fujisan+Onsen+Hotel+Kaneyamaen"],
  tokyo:["Daiwa Roynet Hotel Ginza PREMIER","Chuo-ku Ginza 1-13-15, Tokyo, 104-0061 Japan","東京都中央区銀座1-13-15","Oct 14 after 2:00 PM","Oct 21 before 11:00 AM","Riya Bhangale","Superior Double Room · Non-Smoking","Free cancellation until Oct 13 11:59 PM","https://maps.google.com/?q=Daiwa+Roynet+Hotel+Ginza+PREMIER"],
  seoul:["LOTTE CITY HOTEL MYEONGDONG","362 Samil-daero, Jung-gu, Seoul, South Korea, 04542","중구 삼일대로 362, 서울, 대한민국","Oct 21 after 3:00 PM","Oct 25 before 11:00 AM","Riya Bhangale","Superior Double","Free cancellation until Oct 17 11:59 PM","https://map.naver.com/p/search/LOTTE%20CITY%20HOTEL%20MYEONGDONG"]
 },
 places:{
  osaka:[["LiLo Coffee Roasters","Coffee & Matcha","Saved","Coffee-first morning possibility.","8 min from hotel","https://www.google.com/maps/search/?api=1&query=LiLo+Coffee+Roasters+Osaka"],["Paprika Shokudo","Lunch & Dinner","Saved","Comfort vegan meal in Osaka.","6 min from Shinsaibashi","https://www.google.com/maps/search/?api=1&query=Paprika+Shokudo+Osaka"],["Oko Fun","Lunch & Dinner","Saved","Vegetarian okonomiyaki experience.","4 min from Dotonbori","https://www.google.com/maps/search/?api=1&query=Oko+Fun+Osaka"],["Rikuro Ojisan","Desserts & Bakeries","Maybe Next Time","Iconic fluffy cheesecake.","3 min from Namba","https://www.google.com/maps/search/?api=1&query=Rikuro+Ojisan+Osaka"],["Kuromon Market","Traditional Markets","Saved","Wandering food-street energy near hotel.","5 min from hotel","https://www.google.com/maps/search/?api=1&query=Kuromon+Market+Osaka"]],
  kyoto:[["Weekenders Coffee","Coffee & Matcha","Saved","Beautiful coffee ritual morning.","9 min from hotel","https://www.google.com/maps/search/?api=1&query=Weekenders+Coffee+Kyoto"],["Mumokuteki Cafe","Lunch & Dinner","Saved","Vegetarian Kyoto comfort food.","7 min from hotel","https://www.google.com/maps/search/?api=1&query=Mumokuteki+Cafe+Kyoto"],["Kumo no Chaya","Desserts & Bakeries","Saved","Soft magical dessert stop.","Near Kiyomizu area","https://www.google.com/maps/search/?api=1&query=Kumo+no+Chaya+Kyoto"],["Nishiki Market","Traditional Markets","Saved","Kyoto market wandering.","8 min from hotel","https://www.google.com/maps/search/?api=1&query=Nishiki+Market+Kyoto"]],
  fuji:[["Lake Kawaguchiko Café","Coffee & Matcha","Saved","Coffee with Fuji view.","Near lake route","https://www.google.com/maps/search/?api=1&query=Lake+Kawaguchiko+cafe"],["Ryokan Kaiseki Dinner","Lunch & Dinner","Saved","Dinner as part of the ryokan memory.","At hotel","#"]],
  tokyo:[["Blue Bottle Ginza","Coffee & Matcha","Saved","Easy coffee near home base.","7 min from hotel","https://www.google.com/maps/search/?api=1&query=Blue+Bottle+Ginza"],["T's Tantan","Lunch & Dinner","Saved","Vegan ramen classic.","Near Tokyo Station","https://www.google.com/maps/search/?api=1&query=T's+Tantan+Tokyo"],["Ain Soph Ginza","Lunch & Dinner","Saved","Ginza vegan dining near hotel.","9 min from hotel","https://www.google.com/maps/search/?api=1&query=Ain+Soph+Ginza"],["Tsukiji Outer Market","Traditional Markets","Saved","Morning market experience.","15 min from hotel","https://www.google.com/maps/search/?api=1&query=Tsukiji+Outer+Market"]],
  seoul:[["Plant Café Seoul","Lunch & Dinner","Saved","Reliable vegan comfort in Seoul.","Naver route from hotel","https://map.naver.com/p/search/Plant%20Cafe%20Seoul"],["Osegyehyang","Lunch & Dinner","Saved","Traditional vegetarian meal.","Near Insadong","https://map.naver.com/p/search/Osegyehyang"],["Myeongdong Dessert Walk","Desserts & Bakeries","Unexpected Finds","Leave space for discovery.","Near hotel","https://map.naver.com/p/search/Myeongdong%20dessert"],["Gwangjang Market","Traditional Markets","Saved","Market atmosphere and snacks.","Naver route","https://map.naver.com/p/search/Gwangjang%20Market"]]
 }
};
let state=JSON.parse(localStorage.getItem("ssj")||'{"view":"home","city":"osaka","stack":[],"visited":{}}');
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("ssj",JSON.stringify(state))}
function appShell(){
 $("app").innerHTML=`<div class="app">
 <aside class="sidebar">${brand()}${nav("desktop")}<div class="side-card"><div class="avatar">AR</div><div><b>Aakash & Riya</b><small>Oct 7 – Oct 25, 2026</small></div></div><div class="side-card weather"><div class="sun">☀</div><div><small>Pre-Journey</small><b>92</b><small>days until Japan</small></div></div></aside>
 <main class="main"><div class="mobile-head"><div class="mobile-brand"><div>🌸</div><div><strong>Sakura • Seoul</strong><small>Journal · written together</small></div></div><button class="icon-btn" onclick="more()">☰</button></div>${nav("mobile")}<div class="desktop-top"><button class="back-text" onclick="goBack()">Sakura • Seoul Journal</button><div><button class="icon-btn" onclick="sheet('Search','Search will come later.')">⌕</button><button class="icon-btn" onclick="sheet('Saved','Saved items will live here.')">♡</button><button class="icon-btn" onclick="more()">⋯</button></div></div><div id="context" class="contextbar"></div><section id="root" class="module"></section></main></div>`;
 route(state.view,false);
}
function brand(){return `<div class="brand"><div class="flower">🌸</div><h1>Sakura • Seoul</h1><h2>Journal</h2><p>written together</p></div>`}
function nav(type){let cls=type==="mobile"?"mobile-tabs":"nav desktop-nav";return `<nav class="${cls}">${[["home","🏠","Home"],["journey","🚆","Journey"],["planner","📖","Planner"]].map(x=>`<button data-view="${x[0]}" onclick="route('${x[0]}')" class="${state.view===x[0]?'active':''}">${type==="mobile"?x[1]+' '+x[2]:x[1]+' <span>'+x[2]+'</span>'}</button>`).join("")}${type==="desktop"?`<button onclick="route('readiness')" class="${state.view==='readiness'?'active':''}">⌖ <span>Trip Readiness</span><em>73%</em></button><button onclick="route('budget')">⌬ <span>Budget</span></button><button onclick="route('collections')">◫ <span>Collections</span></button><button onclick="route('memories')">▧ <span>Memories</span></button>`:""}</nav>`}
function setActive(){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view))}
function route(v,push=true){if(push) state.stack.push({view:state.view,city:state.city});state.view=v;save();setActive();render()}
function context(back,title){$("context").innerHTML=`<button onclick="goBack()">← ${back}</button><h2>${title}</h2>`}
function goBack(){let last=state.stack.pop(); if(last){state.view=last.view;state.city=last.city||state.city}else{state.view="home"} save();setActive();render()}
function render(){let r=$("root");$("context").style.display=state.view==="home"?"none":"flex"; if(state.view==="home")home(r); else if(state.view==="journey")journey(r); else if(state.view==="planner")planner(r); else if(state.view==="city")city(r,state.city); else if(state.view==="stay")stay(r,state.city); else if(state.view==="taste")taste(r,state.city); else if(state.view==="itinerary")itinerary(r); else placeholder(r,state.view);}
function train(type){let stops=type==="budget"?[["✈️","Flights","budget"],["🏨","Stay","stay"],["🍜","Taste","taste"],["🚆","Transit","budget"],["🛍","Shop","budget"],["🎟","Tickets","budget"],["📖","Story","memories"]]:[["✈️","Toronto","home"],["🐙","Osaka","osaka"],["⛩","Kyoto","kyoto"],["🗻","Fuji","fuji"],["🗼","Tokyo","tokyo"],["🏙","Seoul","seoul"],["⌂","Home","home"]];return `<div class="train-wrap"><div class="track"></div><div class="train ${type==='budget'?'budget':''}">🚃</div><div class="stops">${stops.map((s,i)=>`<div class="stop ${i<1?'done':''}" onclick="${data.stays[s[2]]?`openCity('${s[2]}')`:s[2]==='taste'?`openTaste()`:`route('${s[2]}')`}"><div class="pin">${s[0]}</div>${s[1]}</div>`).join("")}</div></div>`}
function home(r){r.innerHTML=`<div class="hero-grid"><div class="card welcome"><div class="tag">Foundation 2.0d Alpha 1</div><h1>Good morning,<br>Aakash & Riya</h1><p class="script">Your journal is packed and ready.</p><p class="soft">Open your journey, planner, stays, or Taste & Moments.</p></div><div class="card quote"><p>“The journey begins long before we arrive.”</p></div></div><div class="card"><h3>Journey Spine</h3>${train("journey")}</div><div class="grid three"><div class="card" onclick="placeholder($('root'),'Trip Readiness')"><h3>Trip Readiness</h3><div class="row-between"><div><div class="big">73%</div><p class="soft">Flights and stays are taking shape.</p></div><div class="ring">73%</div></div></div><div class="card" onclick="openCity('osaka')"><h3>Current Chapter</h3><div class="big">Pre-Journey</div><p class="soft">Next: Osaka · Oct 7</p></div><div class="card" onclick="route('planner')"><h3>Today's Plan</h3><p>Continue preparing the journal and city modules.</p></div></div><div class="card"><h3>Budget Train</h3>${train("budget")}</div><div class="banner"><div><h3>Before We Go</h3><p>Bookings, readiness, routes and wishlist.</p></div><div><h3>During The Trip</h3><p>Today's chapter, gentle pauses and maps.</p></div><div><h3>After We Return</h3><p>Pressed leaves, memories and Our Story.</p></div></div>`}
function journey(r){context("Home","Journey");r.innerHTML=`<div class="card"><div class="tag">Journey</div><h1>Japan & Korea</h1><p class="soft">Oct 7 – Oct 25 · five chapters, written together.</p>${train("journey")}</div><div class="list">${data.cities.map(c=>`<button class="list-btn" onclick="openCity('${c[0]}')"><div class="iconbox">${c[1]}</div><div><h3>${c[2]}</h3><small>${c[3]} · ${c[5]}<br>${c[4]}</small></div><span>Open ›</span></button>`).join("")}</div>`}
function openCity(k){state.stack.push({view:state.view,city:state.city});state.city=k;state.view="city";save();setActive();render()}
function city(r,k){let c=data.cities.find(x=>x[0]===k);context("Journey",c[2]);r.innerHTML=`<div class="card hub"><div><div class="tag">City Chapter</div><h1>${c[1]} ${c[2]}</h1><p class="script">${c[3]} · ${c[5]}</p><p class="soft">${c[4]}</p></div><div class="botanical"></div></div><div class="tiles">${tile("🏨","Stay","Quick actions and booking details","stay")}${tile("🍜","Taste & Moments","Cafés, restaurants, markets, memories","taste")}${tile("📖","Itinerary","Today's chapter and gentle pauses","itinerary")}${tile("🚆","Transit","Saved routes and local maps","soon")}${tile("🧭","Explore","Things to do by mood","soon")}${tile("🛍","Shopping","Wishlist and tax-free notes","soon")}</div>`}
function tile(e,t,d,v){return `<button class="card tile" onclick="${v==='soon'?`sheet('${t}','This module is previewed and will be built next.')`:`route('${v}')`}"><div class="emoji">${e}</div><h3>${t}</h3><p class="soft">${d}</p></button>`}
function stay(r,k){let s=data.stays[k];let city=data.cities.find(x=>x[0]===k)[2];context(city,"Stay");let isSeoul=k==="seoul";r.innerHTML=`<div class="stay-top"><div class="card"><div class="tag">${city} · Stay Companion</div><h1>${s[0]}</h1><p class="soft">${s[1]}</p></div><div class="card"><div class="wax">❧</div><p class="script" style="text-align:center">Chapter stay</p></div></div><div class="card quick"><h3>Quick Actions</h3><div class="action-strip"><button class="pill" onclick="window.open('${s[8]}','_blank')">🗺 ${isSeoul?'Naver Maps':'Google Maps'}</button><button class="pill" onclick="copy('${s[2]}')">📋 Copy Address</button><button class="pill" onclick="phrase('${isSeoul?'Korean':'Japanese'}')">💬 Ask in ${isSeoul?'Korean':'Japanese'}</button><button class="pill" onclick="sheet('Contact Hotel','Phone and email shortcuts will be added here.')">☎ Contact</button></div></div><div class="details"><div class="card"><h3>Reservation</h3><div class="info"><div><span>Check-in</span><b>${s[3]}</b></div><div><span>Check-out</span><b>${s[4]}</b></div><div><span>Lead guest</span><b>${s[5]}</b></div><div><span>Room</span><b>${s[6]}</b></div></div></div><div class="card"><h3>Nearby</h3><div class="info"><div><span>Navigation</span><b>${isSeoul?'Naver':'Google'}</b></div><div><span>Coffee</span><b>Taste & Moments</b></div><div><span>Convenience store</span><b>To add</b></div><div><span>More info</span><b>${s[7]}</b></div></div></div></div>`}
function openTaste(){state.view="taste";state.city=state.city||"osaka";save();render()}
function taste(r,k,cat="Coffee & Matcha"){let city=data.cities.find(x=>x[0]===k)[2];context(city,"Taste & Moments");let cats=["Coffee & Matcha","Breakfast & Brunch","Lunch & Dinner","Desserts & Bakeries","Traditional Markets","Unexpected Finds","Visited","Maybe Next Time"];let places=(data.places[k]||[]).filter(p=>cat==="Visited"?state.visited[p[0]]:cat==="Unexpected Finds"?p[2]==="Unexpected Finds":cat==="Maybe Next Time"?p[2]==="Maybe Next Time":p[1]===cat);r.innerHTML=`<div class="card"><div class="tag">${city}</div><h1>Taste & Moments</h1><p class="soft">Curated before the trip. Personal after you visit.</p><div class="tabs">${cats.map(c=>`<button class="tab ${c===cat?'active':''}" onclick="taste($('root'),'${k}','${c}')">${c}</button>`).join("")}</div></div><div class="list">${places.length?places.map(p=>`<button class="list-btn" onclick="place('${k}','${p[0].replaceAll("'","\\'")}')"><div class="place-img">🍜</div><div><h3>${p[0]}</h3><small>${p[1]} · ${p[4]}<br>Why: ${p[3]}</small></div><span class="status">${state.visited[p[0]]?'Visited':p[2]} ›</span></button>`).join(""):`<div class="card"><h3>${cat}</h3><p class="soft">Nothing here yet. This will fill naturally during the journey.</p><button class="pill" onclick="sheet('Unexpected Find','Add-place form will come next.')">+ Add place</button></div>`}</div>`}
function place(k,n){let p=(data.places[k]||[]).find(x=>x[0]===n);let isSeoul=k==="seoul";sheet(p[0],`<div class="photo-hero">🍜</div><p><b>${p[1]}</b> · ${p[4]}</p><p><b>Why we saved it:</b><br>${p[3]}</p><div class="action-strip"><button class="pill" onclick="window.open('${p[5]}','_blank')">🗺 ${isSeoul?'Naver':'Google'} Maps</button><button class="pill" onclick="phrase('${isSeoul?'Korean':'Japanese'}')">💬 Ask in ${isSeoul?'Korean':'Japanese'}</button><button class="pill" onclick="markVisited('${p[0]}')">❤️ Mark Visited</button></div><div class="rating"><button>🌟 We'd happily return</button><button>😊 Glad we came</button><button>🍃 Lovely surprise</button></div>`)}
function markVisited(n){state.visited[n]=true;save();closeSheet();route("taste",false)}
function planner(r){context("Home","Planner");let days=[["Oct 7","Osaka","Arrival · Hotel · Dotonbori"],["Oct 8","Osaka","Coffee · Namba · Shinsaibashi"],["Oct 9","Nara + Uji","Nara Park · Uji matcha"],["Oct 10","Kyoto","Train · Hotel · Gion"],["Oct 12","Fuji","Ryokan · Onsen"],["Oct 14","Tokyo","Ginza check-in"],["Oct 21","Seoul","Myeongdong · Cheonggyecheon"]];r.innerHTML=`<div class="card"><div class="tag">Master Planner</div><h1>Full Trip Timeline</h1><p class="soft">No pressure. Tap a day to open its chapter.</p></div><div class="list">${days.map(d=>`<button class="list-btn" onclick="route('itinerary')"><div class="iconbox">📖</div><div><h3>${d[0]} · ${d[1]}</h3><small>${d[2]}</small></div><span>Open ›</span></button>`).join("")}</div>`}
function itinerary(r){context("Planner","October 8");r.innerHTML=`<div class="card"><div class="tag">Today's Chapter</div><h1>October 8</h1><p class="script">Coffee first. Then the city.</p></div><div class="itin"><div class="timeline">${row("☕","Start","Ease in gently",[["Morning Coffee","Coffee or matcha to begin"]])}${row("⛩","Explore","Main places",[["Dotonbori","Street lights"],["Shinsaibashi","Shopping"],["Hiraoka Park","Green escape"]],pause("💧","Hydrate","Take a moment for water."))}${row("🍜","Recharge","Eat and rest",[["Lunch","Vegetarian options"],["Café Break","Pick a cozy spot"]],pause("🍱","Pause to Eat","How about lunch before you continue?"))}${row("🏮","Wind Down","Evening",[["Canal Walk","Relax and enjoy lights"],["Dessert","Treat yourselves"]],pause("🍰","Treat Yourselves","Maybe today is the day."))}</div><div class="card"><h3>Day Summary</h3><p class="soft">Activities 7 · Gentle Pauses 3 · Cafés 2</p></div></div>`}
function row(e,t,s,items,extra=""){return `<div class="section-row"><div class="phase"><div class="phase-ico">${e}</div><div><h3>${t}</h3><p class="soft">${s}</p></div></div><div class="items">${items.map(i=>`<div class="item" onclick="openTaste()"><span class="dot"></span><div><b>${i[0]}</b><small>${i[1]}</small></div><span>›</span></div>`).join("")}</div>${extra||"<div></div>"}</div>`}
function pause(e,t,s){return `<div class="pause"><div><small class="soft">🌿 Gentle Pause</small><h4>${e} ${t}</h4><p>${s}</p></div><button class="leaf" onclick="this.style.opacity=.5"></button></div>`}
function placeholder(r,t){context("Home",t);r.innerHTML=`<div class="card"><h1>${t}</h1><p class="soft">Preview page. This will be expanded in the next milestone.</p></div>`}
function sheet(title,html){$("sheetBody").innerHTML=`<h1>${title}</h1>${html}`;$("sheet").classList.add("open");$("sheetShade").classList.add("open")}
function closeSheet(){$("sheet").classList.remove("open");$("sheetShade").classList.remove("open")}
function more(){sheet("More",["Trip Readiness","Budget","Collections","Tiny Joys","Memories","Wallet"].map(x=>`<button class="list-btn" onclick="closeSheet();placeholder($('root'),'${x}')"><div class="iconbox">📖</div><div><h3>${x}</h3><small>Open section</small></div><span>›</span></button>`).join(""))}
function copy(t){navigator.clipboard&&navigator.clipboard.writeText(t);sheet("Copied","<p>Address copied.</p>")}
function phrase(lang){sheet("Ask in "+lang,`<p>Phrasebook and ${lang==="Korean"?"Papago":"Translate"} deep link will be added here.</p><p><b>Example:</b> We have a reservation under this name.</p>`)}
$("sheetShade").onclick=closeSheet;
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"))}
appShell();
