const root = document.getElementById('module-root');
const backButton = document.getElementById('backButton');
const sheet = document.getElementById('bottomSheet');
const sheetBackdrop = document.getElementById('sheetBackdrop');
const sheetContent = document.getElementById('sheetContent');
const defaultState = { view:'home', city:'osaka', pressed:{} };
let state = JSON.parse(localStorage.getItem('ssj-state') || JSON.stringify(defaultState));
function save(){ localStorage.setItem('ssj-state', JSON.stringify(state)); }
const trip = {
 cities:[
  {key:'osaka',icon:'🐙',name:'Osaka',dates:'Oct 7–10',nights:'3 nights',hotel:'Sotetsu Grand Fresa Osaka Namba'},
  {key:'kyoto',icon:'⛩',name:'Kyoto',dates:'Oct 10–12',nights:'2 nights',hotel:'Hotel Resol Kyoto Kawaramachi Sanjo'},
  {key:'fuji',icon:'🗻',name:'Fuji',dates:'Oct 12–14',nights:'2 nights',hotel:'Fujisan Onsen Hotel Kaneyamaen'},
  {key:'tokyo',icon:'🗼',name:'Tokyo',dates:'Oct 14–21',nights:'7 nights',hotel:'Daiwa Roynet Hotel Ginza PREMIER'},
  {key:'seoul',icon:'🏙',name:'Seoul',dates:'Oct 21–25',nights:'4 nights',hotel:'LOTTE CITY HOTEL MYEONGDONG'}
 ],
 stays:{
  osaka:{city:'Osaka',hotel:'Sotetsu Grand Fresa Osaka Namba',address:'1-1-13, Nippombashi, Chuo-ku, Osaka, Japan, 542-0073',local:'中央区日本橋1-1-13, 大阪, 日本, 542-0073',checkin:'Oct 7 after 3:00 PM',checkout:'Oct 10 before 11:00 AM',guest:'Riya Bhangale',room:'Economy Double Room · Non-Smoking',nights:'3',request:'Non-smoking, high floor, large bed, quiet room, honeymoon request',cancel:'Free cancellation before Oct 6',map:'https://www.google.com/maps/search/?api=1&query=Sotetsu+Grand+Fresa+Osaka+Namba'},
  kyoto:{city:'Kyoto',hotel:'Hotel Resol Kyoto Kawaramachi Sanjo',address:'59-1 Daikokucho, Nakagyo, Kyoto, Japan, 604-8031',local:'中京区河原町通三条下る大黒町59-1, 京都, 日本, 604-8031',checkin:'Oct 10 after 3:00 PM',checkout:'Oct 12 before 11:00 AM',guest:'Riya Bhangale',room:'Double Room · Non Pet Friendly',nights:'2',request:'Non-smoking, high floor, large bed, quiet room, honeymoon request',cancel:'Free cancellation until Oct 6 11:59 PM',map:'https://www.google.com/maps/search/?api=1&query=Hotel+Resol+Kyoto+Kawaramachi+Sanjo'},
  fuji:{city:'Fuji',hotel:'Fujisan Onsen Hotel Kaneyamaen',address:'9-1-18 Kamiyoshida Higashi, Fujiyoshida, Yamanashi, 403-0032 Japan',local:'9-1-18 Kamiyoshida Higashi, Fujiyoshida, Yamanashi',checkin:'Oct 12 after 3:00 PM',checkout:'Oct 14 before 10:00 AM',guest:'AAKASH IYER',room:'Waraku Yuraku Yamabiko-tei Japanese Style Room with Open-Air Bath Mount Fuji View',nights:'2',request:'Mount Fuji view · Non-smoking',cancel:'Free cancellation until Oct 1',map:'https://maps.google.com/?q=Fujisan+Onsen+Hotel+Kaneyamaen'},
  tokyo:{city:'Tokyo',hotel:'Daiwa Roynet Hotel Ginza PREMIER',address:'Chuo-ku Ginza 1-13-15, Tokyo, 104-0061 Japan',local:'東京都中央区銀座1-13-15',checkin:'Oct 14 after 2:00 PM',checkout:'Oct 21 before 11:00 AM',guest:'Riya Bhangale',room:'Superior Double Room · Non-Smoking',nights:'7',request:'Special requests shared with hotel',cancel:'Free cancellation until Oct 13 11:59 PM',map:'https://maps.google.com/?q=Daiwa+Roynet+Hotel+Ginza+PREMIER'},
  seoul:{city:'Seoul',hotel:'LOTTE CITY HOTEL MYEONGDONG',address:'362 Samil-daero, Jung-gu, Seoul, South Korea, 04542',local:'중구 삼일대로 362, 서울, 대한민국, 04542',checkin:'Oct 21 after 3:00 PM',checkout:'Oct 25 before 11:00 AM',guest:'Riya Bhangale',room:'Superior Double',nights:'4',request:'Stream-facing room',cancel:'Free cancellation until Oct 17 11:59 PM',map:'https://map.naver.com/p/search/LOTTE%20CITY%20HOTEL%20MYEONGDONG'}
 },
 places:{
  osaka:[{name:'Oko Fun',type:'Restaurant',status:'Saved',why:'Vegetarian okonomiyaki experience.',map:'https://www.google.com/maps/search/?api=1&query=Oko+Fun+Osaka'},{name:'Paprika Shokudo',type:'Vegan',status:'Saved',why:'Comfort vegan meal in Osaka.',map:'https://www.google.com/maps/search/?api=1&query=Paprika+Shokudo+Osaka'},{name:'LiLo Coffee Roasters',type:'Café',status:'Saved',why:'Coffee-first morning possibility.',map:'https://www.google.com/maps/search/?api=1&query=LiLo+Coffee+Roasters+Osaka'},{name:'Rikuro Ojisan',type:'Dessert',status:'Maybe Next Time',why:'Iconic fluffy cheesecake.',map:'https://www.google.com/maps/search/?api=1&query=Rikuro+Ojisan+Osaka'}],
  kyoto:[{name:'Weekenders Coffee',type:'Café',status:'Saved',why:'Beautiful coffee ritual morning.',map:'https://www.google.com/maps/search/?api=1&query=Weekenders+Coffee+Kyoto'},{name:'Mumokuteki Cafe',type:'Vegetarian',status:'Saved',why:'Vegetarian Kyoto comfort food.',map:'https://www.google.com/maps/search/?api=1&query=Mumokuteki+Cafe+Kyoto'},{name:'Kumo no Chaya',type:'Dessert',status:'Saved',why:'Soft, magical dessert stop.',map:'https://www.google.com/maps/search/?api=1&query=Kumo+no+Chaya+Kyoto'}],
  fuji:[{name:'Hotel Kaiseki Dinner',type:'Dinner',status:'Saved',why:'Ryokan dinner memory.',map:'#'},{name:'Lake Kawaguchiko Café',type:'Café',status:'Saved',why:'Coffee with Fuji view.',map:'https://www.google.com/maps/search/?api=1&query=Lake+Kawaguchiko+cafe'}],
  tokyo:[{name:"T's Tantan",type:'Vegan Ramen',status:'Saved',why:'Vegan ramen classic.',map:'https://www.google.com/maps/search/?api=1&query=T%27s+Tantan+Tokyo'},{name:'Ain Soph Ginza',type:'Vegan',status:'Saved',why:'Ginza vegan dining near hotel.',map:'https://www.google.com/maps/search/?api=1&query=Ain+Soph+Ginza'},{name:'Blue Bottle Ginza',type:'Café',status:'Saved',why:'Easy coffee near home base.',map:'https://www.google.com/maps/search/?api=1&query=Blue+Bottle+Ginza'}],
  seoul:[{name:'Plant Café Seoul',type:'Vegan',status:'Saved',why:'Reliable vegan comfort in Seoul.',map:'https://map.naver.com/p/search/Plant%20Cafe%20Seoul'},{name:'Osegyehyang',type:'Vegetarian',status:'Saved',why:'Traditional vegetarian meal.',map:'https://map.naver.com/p/search/Osegyehyang'},{name:'Myeongdong Dessert Walk',type:'Dessert',status:'Unexpected Finds',why:'Leave space for discovery.',map:'https://map.naver.com/p/search/Myeongdong%20dessert'}]
 }};
function setActive(view){document.querySelectorAll('.nav-item,.mobile-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function setView(view){state.view=view;save();setActive(view);backButton.textContent=view==='home'?'Sakura • Seoul Journal':'← Back Home';backButton.onclick=()=>setView('home');({home:renderHome,journey:renderJourney,planner:renderPlanner,readiness:()=>placeholder('Trip Readiness will be completed in the next milestone.'),budget:renderBudgetPreview,collections:renderCollections,tinyjoys:()=>placeholder('Tiny Joys will collect delightful moments from each city.'),memories:()=>placeholder('Memories will become your after-trip journal.'),wallet:()=>placeholder('Wallet will hold tickets, QR codes, confirmations and IDs.')}[view]||renderHome)();window.scrollTo(0,0)}
document.querySelectorAll('.nav-item,.mobile-tab').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));document.getElementById('menuButton').onclick=toggleMore;
function placeholder(text){root.innerHTML=`<section class="module"><div class="placeholder">${text}</div></section>`}function openSheet(title,body){sheetContent.innerHTML=`<h2 class="page-title">${title}</h2><p>${body}</p>`;sheet.classList.add('open');sheetBackdrop.classList.add('open')}function closeSheet(){sheet.classList.remove('open');sheetBackdrop.classList.remove('open')}function toggleMore(){openSheet('More',`<div class="place-list">${['Bookings','Trip Readiness','Budget','Collections','Tiny Joys','Memories','Wallet'].map(x=>`<button class="place-row" onclick="closeSheet(); setView('${x.toLowerCase().replaceAll(' ','').replace('tripreadiness','readiness')}')"><div class="city-icon">📖</div><div><h3>${x}</h3><small>Open section</small></div><span>›</span></button>`).join('')}</div>`)}
function renderHome(){root.innerHTML=`<section class="module"><div class="hero-home"><div class="card welcome"><div class="tag">Golden Master · Foundation 2.0</div><h1>Good morning,<br>Aakash & Riya</h1><p class="script">Your journal is packed and ready.</p><p class="soft">Open your journey, planner, stays, or Taste & Moments.</p></div><div class="card quote"><p>“The journey begins long before we arrive.”</p></div></div><div class="card"><h3>Journey Spine</h3>${train('journey')}</div><div class="grid three"><div class="card" onclick="setView('readiness')"><h3>Trip Readiness</h3><div class="progress-row"><div><div class="big-number">73%</div><p class="soft">Flights and stays are taking shape.</p></div><div class="ring">73%</div></div></div><div class="card current-city" onclick="renderCity('osaka')"><h3>Current Chapter</h3><div class="big-number">Pre-Journey</div><p class="soft">Next: Osaka · Oct 7</p></div><div class="card" onclick="setView('planner')"><h3>Today’s Plan</h3><p>Continue preparing the journal and city modules.</p></div></div><div class="card"><h3>Budget Train</h3>${train('budget')}</div><div class="bottom-banner"><div class="banner-card"><h3>Before We Go</h3><p>Bookings, readiness, routes and wishlist.</p></div><div class="banner-card"><h3>During The Trip</h3><p>Today’s chapter, gentle pauses and maps.</p></div><div class="banner-card"><h3>After We Return</h3><p>Pressed leaves, memories and Our Story.</p></div></div></section>`}
function train(type){const stops=type==='budget'?[['✈️','Flights','budget'],['🏨','Stay','budget'],['🍜','Taste','taste'],['🚆','Transit','budget'],['🛍','Shop','budget'],['🎟','Tickets','budget'],['📖','Story','memories']]:[['✈️','Toronto','home'],['🐙','Osaka','osaka'],['⛩','Kyoto','kyoto'],['🗻','Fuji','fuji'],['🗼','Tokyo','tokyo'],['🏙','Seoul','seoul'],['⌂','Home','home']];return `<div class="train-line"><div class="track"></div><div class="train ${type==='budget'?'budget-train':''}">🚃</div><div class="stops">${stops.map((s,i)=>`<div class="stop ${i<1?'done':''}" onclick="${type==='budget'?(s[2]==='taste'?'renderTaste()':`setView('${s[2]}')`):(trip.stays[s[2]]?`renderCity('${s[2]}')`:`setView('${s[2]}')`)}"><div class="pin">${s[0]}</div>${s[1]}</div>`).join('')}</div></div>`}
function renderJourney(){root.innerHTML=`<section class="module"><div class="card"><div class="tag">Journey</div><h1 class="page-title">Japan & Korea</h1><p class="soft">Oct 7 – Oct 25 · five chapters, written together.</p>${train('journey')}</div><div class="city-list">${trip.cities.map(c=>`<button class="city-row" onclick="renderCity('${c.key}')"><div class="city-icon">${c.icon}</div><div><h3>${c.name}</h3><small>${c.dates} · ${c.nights}<br>${c.hotel}</small></div><span>Open ›</span></button>`).join('')}</div></section>`}
function renderCity(key){state.city=key;save();const c=trip.cities.find(x=>x.key===key);setActive('journey');backButton.textContent='← Back to Journey';backButton.onclick=renderJourney;root.innerHTML=`<section class="module"><div class="card hub-hero"><div><div class="tag">City Chapter</div><h1>${c.icon} ${c.name}</h1><p class="script">${c.dates} · ${c.nights}</p><p class="soft">${c.hotel}</p></div><div class="botanical"></div></div><div class="module-grid">${tile('🏨','Stay','Hotel companion and booking details',`renderStay('${key}')`)}${tile('🍜','Taste & Moments','Saved places, visited meals and real-time finds',`renderTaste('${key}')`)}${tile('📖','Itinerary','Today’s chapter and gentle pauses','renderItinerary()')}${tile('🚆','Transit','Saved routes and local maps',`openSheet('Transit','Offline written routes plus Google Maps / Naver links will live here.')`)}${tile('🧭','Explore','Things to do by mood',`openSheet('Explore','Explore will organize places by mood: night, culture, shopping, rain, quiet.')`)}${tile('🛍','Shopping','Wishlist, purchases and tax-free notes',`openSheet('Shopping','Shopping will include Brand Off, ReFa, Muji, Don Quijote, Olive Young and Daiso.')`)}${tile('💰','Budget','City spending and receipts',"setView('budget')")}${tile('📂','Documents','Tickets, confirmations and QR codes',"setView('wallet')")}${tile('🌿','Gentle Pause','Pressed leaves and slow moments','renderCollections()')}</div></section>`}
function tile(icon,title,desc,click){return `<button class="card module-tile" onclick="${click}"><div class="icon">${icon}</div><h3>${title}</h3><p class="soft">${desc}</p></button>`}
function renderStay(key=state.city||'osaka'){const s=trip.stays[key];const country=key==='seoul'?'Korea':'Japan';const mapLabel=key==='seoul'?'Open in Naver Maps':'Open in Google Maps';backButton.textContent=`← Back to ${s.city}`;backButton.onclick=()=>renderCity(key);root.innerHTML=`<section class="module"><div class="stay-hero"><div class="card hotel-title"><div class="tag">${s.city} · Stay Companion</div><h1>${s.hotel}</h1><p class="soft">${s.address}</p><div class="travel-kit"><button class="action-btn" onclick="window.open('${s.map}','_blank')">🗺 ${mapLabel}</button><button class="action-btn" onclick="copyText('${s.local.replaceAll("'",'')}')">📋 Copy Local Address</button><button class="action-btn" onclick="openPhrase('${country}')">💬 Ask in ${country==='Korea'?'Korean':'Japanese'}</button></div></div><div class="card"><div class="wax">❧</div><p class="script" style="text-align:center">Chapter stay</p></div></div><div class="detail-grid">${infoCard('Reservation',[['Lead Guest',s.guest],['Stay',`${s.nights} nights`],['Check-in',s.checkin],['Check-out',s.checkout],['Room',s.room]])}${infoCard('Honeymoon / Request',[['Request',s.request],['Cancellation',s.cancel],['City tax','Collected locally if applicable']])}${infoCard('How to Reach Hotel',[['Primary route','Open saved map link'],['Offline note','Address and station notes remain available'],['Navigation',mapLabel]])}${infoCard('Around the Hotel',[['Convenience store','Saved nearby'],['Station / exit','To be added in Transit'],['Coffee first','Saved in Taste & Moments']])}${infoCard('Before Your Arrival',[['Passport name','Check against reservation'],['Address','Save offline'],['Payment / tax','Review before check-in']])}${infoCard('During / After Stay',[['Room notes','Add during trip'],['His / Her reflection','Available after checkout'],['Open Our Story','Unlocks when chapter is complete']])}</div></section>`}
function infoCard(title,rows){return `<div class="card"><h3>${title}</h3><div class="info-list">${rows.map(r=>`<div class="info-line"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('')}</div></div>`}
function renderTaste(key=state.city||'osaka',filter='Saved'){state.city=key;save();const c=trip.cities.find(x=>x.key===key);const places=trip.places[key]||[];backButton.textContent=`← Back to ${c.name}`;backButton.onclick=()=>renderCity(key);const filters=['Saved','Visited','Unexpected Finds','Maybe Next Time'];root.innerHTML=`<section class="module"><div class="card"><div class="tag">${c.name}</div><h1 class="page-title">Taste & Moments</h1><p class="soft">Saved ideas before the trip. Real memories after you visit.</p><div class="tabs">${filters.map(f=>`<button class="tab ${filter===f?'active':''}" onclick="renderTaste('${key}','${f}')">${f}</button>`).join('')}</div></div><div class="place-list">${places.filter(p=>filter==='Saved'?p.status==='Saved':p.status===filter).map(p=>placeRow(p,key)).join('')||`<div class="card"><h3>${filter}</h3><p class="soft">Nothing here yet. This section will fill naturally as your trip unfolds.</p><button class="action-btn" onclick="openAddPlace('${key}')">+ Add unexpected find</button></div>`}</div></section>`}
function placeRow(p,key){return `<button class="place-row" onclick="openPlace('${key}','${p.name.replaceAll("'","\\'")}')"><div class="city-icon">🍜</div><div><h3>${p.name}</h3><small>${p.type} · Why this place? ${p.why}</small></div><span class="place-status">${p.status} ›</span></button>`}
function openPlace(key,name){const p=(trip.places[key]||[]).find(x=>x.name===name);if(!p)return;const local=key==='seoul'?'Korean':'Japanese';openSheet(p.name,`<p><b>${p.type}</b> · ${p.status}</p><p><b>Why this place?</b><br>${p.why}</p><div class="travel-kit"><button class="action-btn" onclick="window.open('${p.map}','_blank')">🗺 Open in ${key==='seoul'?'Naver':'Google'} Maps</button><button class="action-btn" onclick="openPhrase('${key==='seoul'?'Korea':'Japan'}')">💬 Ask in ${local}</button><button class="action-btn" onclick="markVisited('${key}','${p.name.replaceAll("'","\\'")}')">❤️ Mark Visited</button><button class="action-btn" onclick="markMaybe('${key}','${p.name.replaceAll("'","\\'")}')">🌙 Maybe Next Time</button></div><div class="rating-options"><button>🌟 We'd happily return</button><button>😊 Glad we came</button><button>🍃 Lovely surprise</button><button>📍 Worth visiting</button></div>`)}
function markVisited(key,name){const p=trip.places[key].find(x=>x.name===name);if(p){p.status='Visited';closeSheet();renderTaste(key,'Visited')}}function markMaybe(key,name){const p=trip.places[key].find(x=>x.name===name);if(p){p.status='Maybe Next Time';closeSheet();renderTaste(key,'Maybe Next Time')}}function openAddPlace(key){openSheet('Unexpected Find','<p>Add form will save name, photo, notes and location in a later build.</p><button class="action-btn" onclick="closeSheet()">Save placeholder</button>')}function openPhrase(country){openSheet(country==='Korea'?'Ask in Korean':'Ask in Japanese','<p>Phrasebook + Papago/Translate deep links will live here.</p><p><b>Example:</b> We have a reservation under this name.</p>')}function copyText(text){navigator.clipboard?.writeText(text);openSheet('Copied','Local address copied to clipboard.')}
function renderPlanner(){root.innerHTML=`<section class="module"><div class="card"><div class="tag">Master Planner</div><h1 class="page-title">Full Trip Timeline</h1><p class="soft">No pressure, no over-scheduling. Tap a day to open its chapter.</p></div><div class="planner-list">${plannerRow('Oct 7','Osaka','Arrival · Hotel · Dotonbori')}${plannerRow('Oct 8','Osaka','Coffee · Namba · Shinsaibashi · Hiraoka Park')}${plannerRow('Oct 9','Nara + Uji','Nara Park · Todaiji · Uji matcha')}${plannerRow('Oct 10','Kyoto','Train · Hotel · Gion evening')}${plannerRow('Oct 12','Fuji','Transfer · Ryokan · Onsen')}${plannerRow('Oct 14','Tokyo','Ginza check-in · soft evening')}${plannerRow('Oct 21','Seoul','Flight · Myeongdong · Cheonggyecheon')}</div></section>`}function plannerRow(date,city,desc){return `<button class="planner-row" onclick="renderItinerary()"><div class="city-icon">📖</div><div><h3>${date} · ${city}</h3><small>${desc}</small></div><span>Open ›</span></button>`}
function renderItinerary(){setActive('planner');backButton.textContent='← Back to Planner';backButton.onclick=renderPlanner;root.innerHTML=`<section class="module"><div class="hero"><div class="hero-art"></div><div><div class="tag">Today’s Chapter</div><h1>October 8</h1><div class="city">Osaka, Japan</div><div class="script">Coffee first. Then the city.</div><div class="hero-meta"><span>Weather <b>23°C</b></span><span>Sunrise <b>06:03</b></span><span>Sunset <b>17:32</b></span></div></div><div class="botanical"></div></div><div class="day-tabs"><button class="day-tab">Day 1<br><small>Oct 7</small></button><button class="day-tab active">Day 2<br><small>Oct 8</small></button><button class="day-tab">Day 3<br><small>Oct 9</small></button><button class="day-tab">Day 4<br><small>Oct 10</small></button></div><div class="itinerary-grid"><div class="timeline">${row('☕','Start the Day','Ease in gently',[['Morning Coffee','Coffee or matcha to begin']],'')}${row('⛩','Explore','Main places for today',[['Dotonbori','Street lights and canal energy'],['Shinsaibashi','Shopping and wandering'],['Hiraoka Park','A quiet green escape']],gentle('💧','Hydrate','Take a moment for water before the next adventure.'))}${row('🍜','Pause & Recharge','Rest, eat and enjoy',[['Lunch','Vegetarian options nearby'],['Café Break','Pick a cozy spot'],['Tiny Joy','Something delightful']],gentle('🍱','Pause to Eat','How about a leisurely lunch before you continue?'))}${row('🏮','Wind Down','Evening adventures',[['Dotonbori Night Walk','Vibes and views'],['Canal Walk','Relax and enjoy the lights'],['Dinner','Vegan-friendly picks']],gentle('🍰','Treat Yourselves','You saved a few dessert places nearby. Maybe today is the day.'))}</div><aside class="side-panel"><div class="panel-card"><h3>Day Summary</h3><div class="summary-line"><span>Activities</span><b>7</b></div><div class="summary-line"><span>Gentle Pauses</span><b>3</b></div><div class="summary-line"><span>Cafés</span><b>2</b></div></div><div class="panel-card"><h3>Today’s Map</h3><div class="map-box">Saved route preview</div></div></aside><div class="day-summary"><div><h3>Today’s Summary</h3><div class="stats"><span>Steps <b>18,700</b></span><span>Cafés <b>4</b></span><span>Train rides <b>2</b></span><span>Tiny joy <b>1</b></span></div></div><div class="complete"><div class="seal">❧</div><div><h3>Day Complete</h3><p>See you tomorrow.</p></div></div></div></div></section>`}
function row(icon,title,subtitle,items,pause){return `<div class="section-row"><div class="phase"><div class="phase-icon">${icon}</div><div><h3>${title}</h3><p>${subtitle}</p></div></div><div class="items">${items.map(i=>`<div class="item" onclick="renderTaste(state.city||'osaka')"><span class="dot"></span><div><b>${i[0]}</b><small>${i[1]}</small></div><span>›</span></div>`).join('')}</div>${pause||'<div></div>'}</div>`}function gentle(icon,title,text){return `<div class="gentle-pause"><div><div class="label">🌿 Gentle Pause</div><h4>${icon} ${title}</h4><p>${text}</p></div><button class="press-leaf" onclick="pressLeaf(this)"><span class="leaf"></span><span>Press Leaf</span></button></div>`}function pressLeaf(btn){btn.querySelector('span:last-child').textContent='Pressed';btn.style.opacity='.72';state.pressed[Date.now()]=true;save()}function renderBudgetPreview(){placeholder('Budget train categories are clickable. Full budget details will come in the Budget milestone.')}function renderCollections(){placeholder('Pressed leaves collected from Gentle Pause will appear here.')}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'))}setView(state.view||'home');
